"""add processed storage key

Revision ID: 49a5ff15e0d0
Revises: 6e3eb17c05a2
Create Date: 2026-09-06 20:31:28.454175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a5ff15e0d0'
down_revision: Union[str, Sequence[str], None] = '6e3eb17c05a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processed_storage_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'processed_storage_key')
    # ### end Alembic commands ###
